name: Deploy Flask app to GCP

on:
  push:
    branches: [master]

jobs:
  make_settings_run_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      
      - name: Install python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: echo workspace
        run: echo $GITHUB_WORKSPACE
        shell: bash

      - name: run test
        run: coverage run -m unittest app.py

      - name: test report
        run: coverage report

  build_and_deploy:
    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
      REGION: ${{ secrets.REGION }}
    needs: [make_settings_run_test]
    runs-on: ubuntu-latest
    steps:
      - name: GCP login
        uses: google-github-actions/auth@v1
        with:
          workload_identify_provider: projects/776049473933/locations/global/workloadIdentityPools/github-action-1/*
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        
      - name: Use gcloud CLI
        run: gcloud info
